name: reco-pipeline
channels:
  - conda-forge
dependencies:
  - python=3.12
  - kafka-python
  - fastavro
  - faker
  - click
  - pandas>=2.2
  - pyarrow>=16.1
  - redis-py>=5
  - pytest>=8.1
  - pytest-mock
  - black
  - ruff
  - pip
  - pip:
      - feast==0.44.0 
